name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure Docker to use gcloud as credential helper
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
    
    - name: Create Artifact Registry repository
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        REGION: us-central1
      run: |
        # Create repository if it doesn't exist (ignore error if it exists)
        gcloud artifacts repositories create vite-pwa-test \
          --repository-format=docker \
          --location=$REGION \
          --description="Docker repository for vite-pwa-test" || true
    
    - name: Build and push Docker image
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        IMAGE_NAME: vite-pwa-test
        REGION: us-central1
      run: |
        # Build the Docker image
        docker build -t $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:$GITHUB_SHA .
        docker build -t $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:latest .
        
        # Push the Docker image to Artifact Registry
        docker push $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:$GITHUB_SHA
        docker push $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:latest
    
    - name: Deploy to Cloud Run
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        SERVICE_NAME: vite-pwa-test
        REGION: us-central1
        IMAGE_NAME: vite-pwa-test
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port 8080 \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --timeout 300 \
          --set-env-vars="NODE_ENV=production"
    
    - name: Get service URL
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        SERVICE_NAME: vite-pwa-test
        REGION: us-central1
      run: |
        SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format="value(status.url)")
        echo "Service deployed at: $SERVICE_URL"
        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV
    
    - name: Create deployment comment
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.payload.workflow_run.head_sha,
            body: `🚀 Deployed to Cloud Run: ${{ env.SERVICE_URL }}`
          })